Azure/oav

.gitignore, README.md, ValidationTool.njsproj, ValidationTool.sln, index.js, lib/dataValidator.js, lib/specValidator.js, lib/utils.js
- restructured the source code
- Added a new class named SpecValidator
- Added LicenseHeader in source files
- Updated .gitignore
- Added VisualStudio .njsproj and .sln files (helps while debugging using VS on windows)
- Updated ReadMe.md
=> restrucuture the code base

ValidationTool.njsproj, arm-mediaservices/2015-10-01/swagger/media.json, index.js, lib/specValidator.js, lib/utils.js
- added support for validating examples in spec
- added mediaservice.json swagger spec that contains examples in the spec.
=> added support for validating examples in spec

validate.js
from what I understand we provide an executive summary at the top and
now we're digging into the details, so maybe this message might be a bit
more precise
=> Suggestion to change the result object message

lib/specValidator.js
data/example provided to validate the example - should not be null or undefined.
=> check for null and undefined explicitly.

README.md, index.js, lib/specResolver.js, lib/specValidator.js, lib/util/constants.js, lib/util/utils.js, package.json, validate.js
- 	imp modifications made to run in rest-api-specs CI
- 	improved result construction
=> imp modifications made to run in rest-api-specs CI

lib/util/utils.js, package.json
@salameer - This should take care of SF's concerns.
=> add support for processing swaggers in YAML format

lib/specResolver.js, lib/util/utils.js
=> add support for pure objects #78

index.js, lib/models/index.js, lib/models/potentialOperationsResult.js, lib/util/constants.js, lib/validators/liveValidator.js, lib/validators/specValidator.js, test/liveValidatorTests.js
=> Remodel getPotentialOperations operation to return reasons

lib/models/index.d.ts
Part of https://github.com/Azure/openapi-validation-tools/issues/98
=> updated lib/models/index.d.ts

package.json, scripts/readrecording.js
Adding script to retrieve x-ms-examples data from .net sdk test recordings, to address #18
=> Adding script to retrieve x-ms-examples data from recordings

package.json
Fixes https://github.com/Azure/oav/issues/125
=> Fixing runtime dependency & releasing version 0.4.3

ChangeLog.md, lib/util/utils.js, lib/validators/liveValidator.js, package.json
Fixes: https://github.com/Azure/oav/issues/146
=> Fixed repo cloning logic for live validator

ChangeLog.md, lib/wireFormatGenerator.js, package-lock.json, package.json
https://github.com/Azure/oav/issues/159
=> Wire format generator fixes

ChangeLog.md, lib/util/constants.js, lib/validators/liveValidator.js, lib/validators/specResolver.js, lib/validators/specValidator.js, lib/wireFormatGenerator.js, package-lock.json, package.json, test/liveValidatorTests.js, test/modelValidatorTests.js, test/swaggers/specification/scenarios/resource-manager/Microsoft.Test/2016-01-01/examples/storageAccountCheckNameAvailability.json, test/swaggers/specification/scenarios/resource-manager/Microsoft.Test/2016-01-01/examples/storageAccountPathParameterForwardSlash.json, test/swaggers/specification/scenarios/resource-manager/Microsoft.Test/2016-01-01/examples/storageAccountXmsPaths.json, test/swaggers/specification/scenarios/resource-manager/Microsoft.Test/2016-01-01/examples/storageAccountduplicateforwardslashes.json, test/swaggers/specification/scenarios/resource-manager/Microsoft.Test/2016-01-01/test.json
=> fixes for #140 and #165

README.md, lib/autorestPlugin/pluginHost.js, package.json
Based on latest guidance from autorest, updating plugin configuration. 
Also, addressing formatting out output based on https://github.com/Azure/oav/issues/148
=> Updating model validator plugin to autorest

.vscode/launch.json, ChangeLog.md, lib/validators/specResolver.js, package-lock.json, package.json, test/modelValidation/swaggers/specification/polymorphic/EntitySearch.json, test/modelValidation/swaggers/specification/polymorphic/examples/SuccessfulQueryRequest.json, test/modelValidatorTests.js
- Entire tree except the leaf nodes need to be traversed for replacing references of an uber parent or an intermediate parent with a oneof array containing references to itself and all its children.
This PR should completely fix https://github.com/Azure/oav/issues/142
=> polymorphic model validation

lib/validators/specResolver.js, lib/validators/specValidator.js, test/semanticValidation/specification/definitions/definitions.json, test/semanticValidation/specification/definitions/examples/hello.json, test/semanticValidatorTests.js
Fixes https://github.com/Azure/oav/issues/164
=> Does not error on missing definitions section

lib/autorestPlugin/pluginHost.js
Hey @amarzavery ,
This fixes a critical break when using oav as an autorest extension.
I think there are still at least one or two other glitches; I'm still looking...
=> Fix autorest extension usage

ChangeLog.md, lib/util/utils.js, package.json, test/liveValidation/swaggers/specification/storage/resource-manager/Microsoft.Storage/2016-01-01/live/StorageAccounts_List.json, test/liveValidation/swaggers/specification/storage/resource-manager/Microsoft.Storage/2016-01-01/storage.json, test/liveValidatorTests.js
=> Don't validate pure objects

README.md, test/sampleRequestResponsePair.json
- Add live validation mode to readme.
=> Enhance readme

ChangeLog.md, lib/validators/specValidator.js, test/modelValidation/swaggers/specification/parameterizedhost/examples/SearchServiceCreateOrUpdateDataSource.json, test/modelValidation/swaggers/specification/parameterizedhost/searchservice.json, test/modelValidatorTests.js
@amarzavery @vladbarosan Please review and approve
@salameer FYI...
=> Fix Parameter missing issue with parameterized host extension

lib/models/potentialOperationsResult.ts, lib/validators/liveValidator.ts, lib/validators/specValidator.ts, lib/wireFormatGenerator.ts, package-lock.json, package.json, test/liveValidatorTests.ts, types/yasway.d.ts
- move to yasway, so we don't install from github anymore
=> Move to yasway

lib/validators/specResolver.ts, lib/validators/specTransformer.ts, package-lock.json, package.json
=> Insert title to schema

ChangeLog.md, documentation/oav-errors-reference.md, lib/util/baseValidationError.ts, lib/util/validationError.ts, lib/validators/modelValidator.ts, lib/validators/specResolver.ts, package-lock.json, package.json, test/modelValidation/swaggers/specification/polymorphic/examples/CircularAnimal_IncorrectSibling_List.json, test/modelValidatorTests.ts
- On array of inner errors, after flattening, eliminate duplicates
- retain the paths for where those occurred
=> Add unique array errors

.vscode/launch.json, ChangeLog.md, lib/validate.ts, package-lock.json, package.json
=> Fix for `resolve-spec` CLI #320

.vscode/launch.json, ChangeLog.md, lib/validators/resolveNestedDefinitions.ts, package-lock.json, package.json, test/errorInfoTests.ts, test/modelValidation/swaggers/specification/errorInfo/apimusers.json, test/modelValidation/swaggers/specification/errorInfo/examples/ApiManagementPutUsers.json
We use `title` to provide source map info to yasway. We need to provide `title` for all Schema Objects.
=> Provide schema information for all Schema Objects.

.vscode/launch.json, ChangeLog.md, index.ts, lib/util/documents.ts, lib/util/jsonUtils.ts, lib/util/makeRequest.ts, lib/util/utils.ts, lib/validate.ts, lib/validators/specResolver.ts, lib/validators/specValidator.ts, lib/wireFormatGenerator.ts, package-lock.json, package.json, test/modelValidation/swaggers/specification/suppressions3/examples/storageAccountCheckNameAvailability.json, test/modelValidation/swaggers/specification/suppressions3/readme.md, test/modelValidation/swaggers/specification/suppressions3/test.json, test/suppressionTests.ts
@vladbarosan Here's the real changes https://github.com/Azure/oav/pull/360/commits/f7be75c44f43631fd1ad917a563e8a957041c81d
Everything else is just restructure.
=> Suppress errors in suppression readme

ChangeLog.md, lib/util/processErrors.ts, lib/util/validationError.ts, lib/validators/modelValidator.ts, lib/validators/specResolver.ts, package.json
=> No symbol logging

.vscode/launch.json, ChangeLog.md, lib/util/processErrors.ts, lib/validators/modelValidator.ts, lib/validators/semanticValidator.ts, lib/validators/specTransformer.ts, package.json, test/invalidExamplesTests.ts, test/modelValidation/swaggers/specification/invalidExamples/cdn.json, test/modelValidation/swaggers/specification/invalidExamples/examples/Profiles_Create.json, test/modelValidatorTests.ts
=> Fix for #379

ChangeLog.md, lib/util/jsonUtils.ts, lib/validators/specResolver.ts, package-lock.json, package.json
Add detail error when load invalid local reference file or empty file.
[Issue#449](https://github.com/Azure/oav/issues/449), 
[Issue#444](https://github.com/Azure/oav/issues/444)
=> Fixed internal errors when load local reference file

ChangeLog.md, lib/validators/liveValidator.ts, package-lock.json, package.json
Added an optional logging callback to consume by livevalidator to dump
logs to external caller.
=> Improve logging for livevalidator

ChangeLog.md, lib/util/constants.ts, lib/util/utils.ts, lib/validators/liveValidator.ts, package-lock.json, package.json, test/liveValidation/payloads/enumCaseMismatch_input.json, test/liveValidation/payloads/enumMismatch_input.json, test/liveValidation/payloads/invalidFormat_input.json, test/liveValidation/payloads/invalidType_input.json, test/liveValidation/payloads/maxLength_input.json, test/liveValidation/payloads/missingRequiredParameter_input.json, test/liveValidation/payloads/multipleErrors_input.json, test/liveValidation/payloads/objectAdditionalProperties_input.json, test/liveValidation/payloads/objectMissingRequiredProperty_input.json, test/liveValidation/payloads/oneOfMissing_input.json, test/liveValidation/payloads/piiMismatch_input.json, test/liveValidation/payloads/secretProperty_input.json, test/liveValidation/payloads/unresolvableReference_input.json, test/liveValidation/payloads/valid_input.json, test/liveValidatorTests.ts
Add corrleationId;
Log execution time for each operation;
Log splited request info for each call.
=> Extends logging and metrics.

ChangeLog.md, lib/validators/liveValidator.ts, package-lock.json, package.json, test/liveValidatorTests.ts, test/sample.ts
Change the swaggerPathPattern to array type from string.
=> Task #1032251 live validator swaggerPathPattern

azure-pipelines-securitytasks.yml, credScanSuppressions.json
=> Add security tasks to CI build pipeline

ChangeLog.md, package-lock.json, package.json
Update the version of z-schema and yasway
=> Update the version of z-schema and yasway

ChangeLog.md, lib/util/utils.ts, lib/validators/liveValidator.ts, package-lock.json, package.json, test/liveValidation/swaggers/specification/authorization/resource-manager/Microsoft.Authorization/preview/2018-09-01-preview/authorization-RoleAssignmentsCalls.json, test/liveValidatorTests.ts
Fall back to match operations in cache to child resouces if having both
of parent and child resouces in request url.
=> Fall back to child resouce match for liveValidator

ChangeLog.md, lib/validate.ts, package-lock.json, package.json
Upgraded openapi-markdown pkg version.
=> Upgraded package version.

ChangeLog.md, lib/validators/liveValidator.ts, package-lock.json, package.json, test/liveValidation/swaggers/specification/unknown-rp/unknown.json, test/liveValidatorTests.ts
added check when search in unknownrp->unknownapiversion;
added unit test.
=> Fixed typeerror when search in unknownapiversion.

package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/readonlyProperty_input.json, test/liveValidation/swaggers/specification/contoso/resource-manager/Microsoft.Contoso/2020-01-01/contoso.json, test/liveValidatorTests.ts
add the test case for x-ms-mutability read
Version of OAV is not updated yet to combine with other changes.
=> Update the version of yasway

ChangeLog.md, lib/validate.ts, package-lock.json, package.json
Pretty switch is used when call OAV from pipeline, output the log when exception happens.
=> Output the exception information when pretty switch is enabled

lib/validate.ts, test/liveValidation/payloads/fooResourceProvider_input.json, test/liveValidation/swaggers/specification/resources/resource-manager/Microsoft.Resources/2015-11-01/resources.json, test/liveValidatorTests.ts
Add test case to verify the bahaviour
=> It looks the problem of microsoft.resources was already resolved. 

ChangeLog.md, lib/util/utils.ts, package-lock.json, package.json, test/modelValidation/swaggers/specification/source-map/Microsoft.ADHybridHealthService/stable/2014-01-01/examples/AddomainServiceMembers.json, test/sourceMapTests.ts
Avoid adding nullable value for parameter when its' type isn't string.
=> Fixed nullable value bug

ChangeLog.md, package-lock.json, package.json
Removed clonedeep from yasway;
package security fix.
=> Merge from master@0.22.1

ChangeLog.md, index.ts, package-lock.json, package.json
* Export more methods from oav for validation in unified pipeline
* minor
* add change log and bump version
Co-authored-by: t-zhangw <codespace@72c482c53b75>
=> Export more methods from oav for validation in unified pipeline (#523)

ChangeLog.md, lib/util/validationError.ts, package-lock.json, package.json, regression/__snapshots__/validateExamplesRegression_latestOnly.test.ts.snap, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/MultiplepathPayload_input.json, test/liveValidation/swaggers/specification/hybridnetwork/resource-manager/2020-01-01-preview/common.json, test/liveValidation/swaggers/specification/hybridnetwork/resource-manager/2020-01-01-preview/vendor.json, test/liveValidatorTests.ts
* Fix the additional path item problem for error path
* Update snapshot file
* Support writeonly property
* Apply the change for write_only property
* Update the version of OAV
Co-authored-by: FAREAST\renhel <renhel@microsoft.com>
=> merge from master to release

lib/util/getErrorsFromSemanticValidation.ts
Co-authored-by: t-zhangw <codespace@72c482c53b75>
=> Fix name ONR_OF_MULTIPLE to ONE_OF_MULTIPLE (#536)

ChangeLog.md, package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/valid_inputOptionalParameterBodyEmpty.json, test/liveValidation/payloads/valid_inputOptionalParameterBodyNull.json, test/liveValidation/swaggers/specification/contoso/resource-manager/Microsoft.Contoso/2020-01-01/contoso.json, test/liveValidatorTests.ts
to treat {} and null for parameter body with the same behavour
=> Apply the latest change for yasway 

ChangeLog.md, package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/valid_inputOptionalParameterBodyEmpty.json, test/liveValidation/payloads/valid_inputOptionalParameterBodyNull.json, test/liveValidation/swaggers/specification/contoso/resource-manager/Microsoft.Contoso/2020-01-01/contoso.json, test/liveValidatorTests.ts
=> Merge from master into release

ChangeLog.md, package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/xmsSecretAndRequired.json, test/liveValidation/swaggers/specification/contoso/resource-manager/Microsoft.Contoso/2020-01-01/contoso.json, test/liveValidatorTests.ts
Only in case of both required and x-ms-secret:true are annotated.
=> Ignore required rule check in response.

ChangeLog.md, lib/validators/modelValidator.ts, lib/validators/specResolver.ts, test/modelValidation/swaggers/specification/invalidExamples/missingExampleReference.json, test/modelValidatorTests.ts
Output model detail in log when resolve it with failure,
report error when the example reference has issues.
=> Fixed two bugs in error handling

ChangeLog.md, lib/validators/modelValidator.ts, lib/validators/specResolver.ts, package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/xmsSecretAndRequired.json, test/liveValidation/swaggers/specification/contoso/resource-manager/Microsoft.Contoso/2020-01-01/contoso.json, test/liveValidatorTests.ts, test/modelValidation/swaggers/specification/invalidExamples/missingExampleReference.json, test/modelValidatorTests.ts
- Output model detail in log when resolve it with failure.
- Report error when the example reference is not defined or is not correct.
- Ignore required validation rule in response when x-ms-secret is true.
=> Merge from master @0.22.9

lib/liveValidation/operationValidator.ts, lib/swaggerValidator/schemaValidator.ts, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/lro_responsecode_error_input.json, test/liveValidation/swaggers/specification/servicelinker/resource-manager/Microsoft.ServiceLinker/preview/2021-01-01-privatepreview/servicelinker.json
Asynchronous DELETE operation must return 202, + 200, 204
Asynchronous PATCH operation must return 202 or 201, +  200 
Asynchronous POST operation must return 202 or 201 , + 200, 204
Asynchronous PUT operation must return 200 or 201 or 202
=> Update LRO rules for adding allowed response code

ChangeLog.md, lib/commands/analyze-dependency.ts, lib/commands/generate-collection.ts, lib/commands/generate-test-static-scenario.ts, lib/commands/run-test-scenario.ts, lib/inversifyUtils.ts, lib/testScenario/_testStorage.ts, lib/testScenario/dependencyAnalyzer.ts, lib/testScenario/gen/staticTestScenarioGenerator.ts, lib/testScenario/postmanCollectionGenerator.ts, lib/testScenario/postmanCollectionRunnerClient.ts, lib/testScenario/postmanReportParser.ts, lib/testScenario/swaggerAnalyzer.ts, lib/testScenario/testResourceLoader.ts, package-lock.json, package.json
=> oav2.3.1 dependency analyze. auto genereate test-scenario. run test scenario

ChangeLog.md, index.ts, lib/validators/liveValidator.ts, package-lock.json, package.json
Catch error in loading the swagger.
=> Improve logging and add export some functions

ChangeLog.md, index.ts, lib/validators/liveValidator.ts, package-lock.json, package.json
* Improve logging and export some functions
* Catch error in spec initialization
=> Improve logging and add export some functions (#611)

index.ts, lib/liveValidation/liveValidator.ts, lib/liveValidation/operationSearcher.ts, lib/liveValidation/operationValidator.ts, package-lock.json
output log when build validator on demand;
export some types in utils.
=> Add more loggings and export types

ChangeLog.md, lib/commands/run-test-scenario.ts, lib/exampleQualityValidator/exampleQualityValidator.ts, lib/testScenario/_testPostmanReportParser.ts, lib/testScenario/blobUploader.ts, lib/testScenario/dataMasker.ts, lib/testScenario/defaultNaming.ts, lib/testScenario/postmanCollectionGenerator.ts, lib/testScenario/postmanCollectionRunnerClient.ts, lib/testScenario/postmanReportAnalyzer.ts, lib/testScenario/postmanReportParser.ts, lib/testScenario/postmanTestScript.ts, lib/testScenario/reportGenerator.ts, lib/testScenario/swaggerAnalyzer.ts, lib/testScenario/testResourceLoader.ts, lib/testScenario/testResourceTypes.ts, lib/util/severity.ts, package-lock.json, package.json, test/testScenario/dataMaskerTest.ts
add code severity
support load resource type
output all file to outputFolder
=> optimise upload blob path and report format

ChangeLog.md, index.ts, lib/liveValidation/liveValidator.ts, lib/liveValidation/operationSearcher.ts, lib/liveValidation/operationValidator.ts, package-lock.json, package.json
Added loggingType to differentiate the log;
Added dedicated perf loggings.
=> Supports different logging types in livevalidator

ChangeLog.md, index.ts, lib/liveValidation/liveValidator.ts, lib/liveValidation/operationValidator.ts, package-lock.json, package.json, test/__snapshots__/liveValidatorTests.ts.snap, test/liveValidation/payloads/missingResourceId_input.json, test/liveValidation/payloads/missingResourceId_sublevelResource_input.json, test/liveValidation/swaggers/specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/preview/2015-11-01-preview/OperationsManagement.json, test/liveValidation/swaggers/specification/servicelinker/resource-manager/Microsoft.ServiceLinker/preview/2021-01-01-privatepreview/servicelinker.json, test/liveValidatorTests.ts
Ignore sub level resources in response validation for missing_resource_id rule
Added test case
=> Ignore sub level resources validation for missing_resource_id rule

ChangeLog.md, lib/liveValidation/liveValidator.ts, lib/liveValidation/liveValidatorLoader.ts, lib/liveValidation/operationSearcher.ts, lib/liveValidation/operationValidator.ts, lib/swagger/swaggerTypes.ts, lib/transform/allOfTransformer.ts, lib/transform/context.ts, lib/transform/discriminatorTransformer.ts, lib/transform/nullableTransformer.ts, lib/util/errorDefinitions.ts, package-lock.json, package.json, tsconfig.json
- Isolate RP when running transform on cached models in livevalidator
- Fix type error in nullableTransformer
- Throw exception when getting error in transformLoadedSpecs at livevalidator initialization
- Improve wording of error messages
=> Live validator update from rpaas feedback
